version: '3.8'

services: 
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on: 
      - db
    environment: 
      - "DJANGO_SECRET_KEY=jl=w*!ug)=2urw5p^hu#h+uqi10ar^myp4&zl1lplou@^gz52f"
      - "DJANGO_DEBUG=True"
      - "DJANGO_SECURE_SSL_REDIRECT=False"
      - "DJANGO_SECURE_HSTS_SECONDS=0"
      - "DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS=False"
      - "DJANGO_SECURE_HSTS_PRELOAD=False"
      - "DJANGO_SESSION_COOKIE_SECURE=False"
      - "DJANGO_CSRF_COOKIE_SECURE=False"
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes: 
  postgres_data: