# Generated by Django 3.1.6 on 2021-02-07 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('speacial_status', 'can read all books')]},
        ),
    ]
